### ISSUE TITLE
error when following case study: Studying the evolution citrate utilization in the Long Term Evolution Experiment.

### ISSUE THREAD

**Issue by beacamara** [segrelab/cometspy#11]
Hello again!
 I am following the examples in the documentation in order to get used of comets. In the case study of "Studying the evolution citrate utilization in the Long Term Evolution Experiment", an error came up when running comets in the second phase of the experiment  (marked in bold in the code below)

# At roughly Generation 31,000 we introduce the CitT genotype and run for around 2000 Generations
batch_test.layout.models[0].initial_pop = [0, 0, float(batch_test.total_biomass.Ancestor.tail(1))]
batch_test.layout.models[1].initial_pop = [0, 0, 3.9e-11]
_batch_test.layout.build_initial_pop() # not present in the current version of comets
batch_test.parameters.set_param('maxCycles', int(300*cycles_per_day))
**batch_test.run()**

Here is the error that I obtain. I do not understand from where it comes from, as when I run the code manually I can not see an error. The build_initial_pop() is not present in the current version of comets. I do not know if this can be the reason of the error. Or something related to the local configuration of my computer as it occurred in past issues or maybe something I did wrong or I didn't do. Could you help me to figure out what is happening?

Thank you so much

Beatriz
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/cometspy/comets.py", line 361, in run
    self.layout.write_necessary_files(self.working_dir, to_append)
  File "/usr/local/lib/python3.8/dist-packages/cometspy/layout.py", line 633, in write_necessary_files
    self.__check_if_initial_pops_in_range()
  File "/usr/local/lib/python3.8/dist-packages/cometspy/layout.py", line 1418, in __check_if_initial_pops_in_range
    for founder in m.initial_pop:
TypeError: 'int' object is not subscriptable

**Comment by djbajic** [comment]
Hola Bea, 

I apologize for this. We have made some changes to cometspy lately to fix some bugs that we were catching, and I think you have an outdated version. You should just upgrade your cometspy, using `pip install cometspy --upgrade`. 

Oh, and also, the function `build_initial_pop` is outdated, just use `update_models()` instead.

**Comment by beacamara** [comment]
Hello again,
I have update cometspy, and now my script is not working anymore. I think the new version has something that modify the c.model function. Below you will find the error message related to line 115 of  model.py

model_modifications(glu1, ac1, o21, glu2, ac2, o22)
  File "/media/Backup/disk1/bcamara/portatil_acer/CNB_globachem/software/FLYCOP/FLYCOP-master/Scripts/ecoliLongTermFLYCOP.py", line 29, in model_modifications
    model1=c.model('/media/Backup/disk1/bcamara/portatil_acer/CNB_globachem/software/FLYCOP/FLYCOP-master/test/iJO1366.cmd')
  File "/home/bcamara/.local/lib/python3.8/site-packages/cometspy/model.py", line 115, in __init__
    self.read_comets_model(model, randomtag)
TypeError: read_comets_model() takes 2 positional arguments but 3 were given

**Comment by beacamara** [comment]
Hello,
I have modified the code of my script in order to read the model using cobrapy and then cometspy. However, another error came up, related to the function of c.layout(file)

layout=c.layout(file)
  File "/home/bcamara/.local/lib/python3.8/site-packages/cometspy/layout.py", line 132, in __init__
    self.read_comets_layout(input_obj)
  File "/home/bcamara/.local/lib/python3.8/site-packages/cometspy/layout.py", line 408, in read_comets_layout
    curr_model = model(model_path)
  File "/home/bcamara/.local/lib/python3.8/site-packages/cometspy/model.py", line 115, in __init__
    self.read_comets_model(model, randomtag)
TypeError: read_comets_model() takes 2 positional arguments but 3 were given


Enclosed you will finde a screenshot of the layout file. As you can see the models are in .cmd format. And when cometspy internally try to read this models with the c.model() function, an error comes up, but this error does not appear when the model is first read using cobrapy.

![Captura de pantalla de 2021-07-01 11-37-21](https://user-images.githubusercontent.com/11525843/124102546-c0207400-da60-11eb-9334-1f4371e10176.png)

Here you will find the different examples I have tried to come to this conclusion

>>> test_model = cobra.test.create_test_model('textbook')
>>> test_model = c.model(test_model)

>>> model_ecoli_cometspy_read = c.model('/home/bcamara/iJO1366.cmd')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bcamara/.local/lib/python3.8/site-packages/cometspy/model.py", line 115, in __init__
    self.read_comets_model(model, randomtag)
TypeError: read_comets_model() takes 2 positional arguments but 3 were given
>>> model_ecoli = cobra.io.read_sbml_model('/media/Backup/disk1/bcamara/portatil_acer/CNB_globachem/software/FLYCOP/FLYCOP-master/test/iJO1366.xml')
>>> model_ecoli_cometspy = c.model(model_ecoli)
>>> model1=c.model('/media/Backup/disk1/bcamara/portatil_acer/CNB_globachem/software/FLYCOP/FLYCOP-master/test/iJO1366.cmd')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bcamara/.local/lib/python3.8/site-packages/cometspy/model.py", line 115, in __init__
    self.read_comets_model(model, randomtag)
TypeError: read_comets_model() takes 2 positional arguments but 3 were given

**Comment by djbajic** [comment]
That is a bug arising from the last update. I fixed it now, please upgrade your package again and you should be ready to go.

**Comment by beacamara** [comment]
Thank you djbajic for you quick answer. However, the error still arises when I execute my script. It is also related to line 115 of layout.py. Enclosed you will find a screenshot of the error.

It seems that the function self.read_comets_model(model, randomtag) of layout.py has only two arguments but it is receiving three. 

/home/bcamara/.local/lib/python3.8/site-packages/cometspy/model.py
![Captura de pantalla de 2021-07-02 09-28-16](https://user-images.githubusercontent.com/11525843/124237483-dc331c80-db17-11eb-8244-7c4873840d25.png)

**Comment by djbajic** [comment]
I don't understand at this point what is going on. That should be fixed, and indeed it works on my side when I test it, e.g. ltrying to load a comets layout file. The function takes

**Comment by beacamara** [comment]
I do not understand also what is happening.  Because before the last update, the script was working perfectly, and then after the update the script crashes.
Following your suggestions, I have uninstall and reinstall cometspy. And then I have tryied to read a model in .cmd format using the c.model function. Also, I have tried to read a simple layout file and it does not work.


![Captura de pantalla de 2021-07-05 08-54-16](https://user-images.githubusercontent.com/11525843/124429865-b489c180-dd6e-11eb-811c-187e2d87b1c3.png)
![Captura de pantalla de 2021-07-05 08-31-55](https://user-images.githubusercontent.com/11525843/124429868-b5225800-dd6e-11eb-9d53-de946feb5a92.png)

**Comment by djbajic** [comment]
I am really puzzled, because with cometspy 0.4.13, I am able to run your code without errors. 

Could you please show me the output of `c.model.read_comets_model`

**Comment by beacamara** [comment]
Me too. I also do not understand what is going on. Here is the output of the c.model.read_comets_model. 
I hope it helps. I am going to test the code in other computers. I will let you know.


![Captura de pantalla de 2021-07-06 09-17-23](https://user-images.githubusercontent.com/11525843/124558607-13b50800-de3b-11eb-96f0-5eb7296eb84b.png)

**Comment by beacamara** [comment]
Hello djbajic,
I have finally found out what was going on. The problem was related to the cometspy version that my system was executing. I updated the last version of cometspy in the system, but python was using a local version of python which had a version of cometspy 0.4.12 and for that reason the error was still there.
My apologies for any inconvenience caused.
Thank you for you time and patience

**Comment by djbajic** [comment]
Great, glad we managed to solve it!

**Comment by MOUHRACH** [comment]
Hi everyone! HELP
I am trying to use COMETSpy to run a two-species simulation in a Petri dish. However, I consistently encounter the following error shortly after world construction and the start of processing cycles, which interrupts the simulation and prevents it from completing. Has anyone else encountered this error with a two-species model? Note: the single-species simulation works correctly.


<img width="641" height="343" alt="Image" src="https://github.com/user-attachments/assets/f530dea9-50c3-4870-8c8a-4f64478220ea" />
